{% set name = "mdanalysis-sphinx-theme" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdanalysis_sphinx_theme-{{ version }}.tar.gz
  sha256: 301b28338699dd922d7d1fac5f86083f0070955f004c8ab34fb56737bf6c272c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - beautifulsoup4
    - css-html-js-minify
    - libsass
    - lxml
    - python-slugify
    - sphinx >=6.2.1,<7.0
    - sphinx_rtd_theme


test:
  imports:
    - mdanalysis_sphinx_theme
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MDAnalysis/mdanalysis-sphinx-theme
  summary: 'A Sphinx Theme for MDAnalysis'
  description: |
    This is a Sphinx theme for MDAnalysis. It is a modification of
    `sphinx_rtd_theme` based on
    `msmb_theme` and `openff-sphinx-theme`.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://mdanalysis-sphinx-theme.readthedocs.io/en/latest/
  dev_url: https://github.com/MDAnalysis/mdanalysis-sphinx-theme

extra:
  recipe-maintainers:
    - lilyminium
